[profile.default]
src = "src"
test = "test"
script = "script"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true

fs_permissions = [
    { access = "read-write", path = "./deployments" }
]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]