[profile.default]
src = "src"
test = "test"
script = "script"
libs = ["lib"]
fs_permissions = [
    { access = "write", path = "./deployments" }
]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]